apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_HOST: 136.112.124.44
  DB_PORT: 5432
  DB_USER: postgres   
  DB_PASSWORD: Saikethan@0010723
  DB_NAME: products_db
